# Generated by Django 2.2.7 on 2020-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('help_type', models.CharField(choices=[('can_help', 'Хочу помочь'), ('need_help', 'Нужна помощь')], max_length=20)),
                ('city', models.CharField(max_length=100, verbose_name='Город/село')),
                ('info', models.TextField(verbose_name='Описание')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ' Запрос ',
                'verbose_name_plural': 'Запросы',
                'ordering': ['-date_pub'],
            },
        ),
    ]
